 # Fundamentals of Tensors using Tensorflow
 

## Intro to Tensors

In [1]:
#Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [2]:
# Create tensor with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check no of dimensions of tensor (ndim = no of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#check dim of vector
vector.ndim

1

In [6]:
# Create a Matrix
matrix=tf.constant([[10,7],
                   [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
#Create another matrix
another_matrix=tf.constant([[10. ,7.],
                            [3.,2.],
                            [8.,9.]
                            ],dtype=tf.float16)#specifying datatype with dtype parameter
                            

In [9]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
# Let's create a Tensor
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                     [[7,8,9],
                     [10,11,12]],
                     [[13,14,15],
                     [16,17,18]]])

In [12]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

##Scalar:Single number
##Vecotor:Number with direction
##Matrix:2 dim array of numbers
##Tensor:N-dim array of numbers(N lies between 0 to  inf.)

## Creating Tensor with tf.Variable

In [14]:
tf.Variable 

tensorflow.python.ops.variables.Variable

In [15]:
#Create the same tensor with tf.var as above
changable_tensor=tf.Variable([10,7])
unchangable_tensor=tf.constant([10,7])
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
#Lets try changing elemenets of changable tensor
changable_tensor[0]=7
changable_tensor

TypeError: ignored

In [17]:
#Use .assign()
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [18]:
 #Lets try unchangeable tensor
 unchangable_tensor[0].assign(7)

AttributeError: ignored

## Creating Random tensors
Random Tensors are tensors of arbitrary size with random numbers


In [19]:
#Create 2 random (equal) tensors
random_1=tf.random.Generator.from_seed(42)#set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [20]:
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [21]:

#Are those equal
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle elements in a tensor

### Shuffle the order of element in tensor

*   List item
*   List item



In [22]:

#Shuffle a  Tensor (valuable for when U want to shuffle your data so the inherent order doesnt effect learning )
not_shuffled=tf.constant([[10,7],
                           [3,4],
                           [2,5]
                           ])
not_shuffled.ndim

2

In [23]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [24]:
tf.random.set_seed(42)#change hoke constant rhege order ,global lv seed
tf.random.shuffle(not_shuffled,seed=42) # operational lv random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

  ## Other ways to make Tensors

In [25]:
tf.ones([10,7])#Tensor of all 1

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [26]:
tf.zeros(shape=(3,4))#All Zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [27]:
# U cn turn numpy arrays into Tensors
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [28]:
A=tf.constant(numpy_A,shape=(3,8))
A

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [29]:
A.ndim

2

## Getting Information from Tensors
When dealing with Tensors you want to be aware of the following attributes:

*Shape
*Rank
*Axis of Dim
*Size

In [30]:
#Create a rank 4 tensor (4 dim)
ranked_4_tensor=tf.zeros(shape=(2,3,4,5))


In [31]:
ranked_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
ranked_4_tensor.ndim

4

In [33]:
ranked_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [34]:
ranked_4_tensor.shape,ranked_4_tensor.ndim,tf.size(ranked_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [35]:
#Get various attributes of our Tensor
print("Datatype of every element:",ranked_4_tensor.dtype)
print("Number of Dimensions (rank):",ranked_4_tensor.ndim)
print("Shape of Tensor:",ranked_4_tensor.shape)
print("Elements along 0 axis:",ranked_4_tensor.shape[0])
print("Elements along Last axis:",ranked_4_tensor.shape[-1])
print("Total no of elements:",tf.size(ranked_4_tensor))

Datatype of every element: <dtype: 'float32'>
Number of Dimensions (rank): 4
Shape of Tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along Last axis: 5
Total no of elements: tf.Tensor(120, shape=(), dtype=int32)


### Indexing Tensors
They can be indexed like Python List

In [36]:
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [37]:
#Get the first 2 elements of each Dimension
ranked_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [38]:
some_list[:1]

[1]

In [39]:
#Get first element from each dimension from each index except for the final one
ranked_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [40]:
#Create a Rank 2 Tensor
rank_2_tensor=tf.constant([[10,7],
                           [3,4]])

In [41]:

rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [42]:
#Get last element of Each row
rank_2_tensor[:,-1]#sari rows : aa gyi and last wala column decide krega

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [43]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [44]:
#Add extra dimension to our rank 2 tensor , In NN their (tensor) shape will lingn up
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [45]:
#Alternate to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)#-1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [46]:
tf.expand_dims(rank_2_tensor,axis=0)#Expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

#Manipulating Tensors (tensors operations)
**Basic operations
+,-,'x',/

In [47]:
# You can add value to a tensor using the addition operator
tensor=tf.constant([[10,7],[3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [48]:
#Original tensor is unchanged
tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [49]:
#Multiplication also works
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [50]:
#Subtraction
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [51]:
#Using built-in function
tf.multiply(tensor,10)#Opertion will speed up on GPU using tf built in operations

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [52]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [53]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

** Matrix Multiplication **

In [54]:
#In ML ,matrix multiplication is most comman tensor operation
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [55]:
tf.matmul(tensor,tensor)#Matrix multiplication ,. product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [56]:
tensor *tensor#its element wise 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [57]:
#Excersise 1
mat1=tf.constant([[1,2,5],[7,2,1],[3,3,3]])
mat1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

In [58]:
mat2=tf.constant([[3,5],[6,7],[1,8]])
mat2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [59]:
tf.matmul(mat1,mat2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [60]:
tensor.shape

TensorShape([2, 2])

In [61]:
#Let's try multiply tensors of same shape
mat2 @ mat2 #Size incaptiable

InvalidArgumentError: ignored

In [62]:
tf.reshape(mat2,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]], dtype=int32)>

In [63]:
mat1,tf.transpose(mat1)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 7, 3],
        [2, 2, 3],
        [5, 1, 3]], dtype=int32)>)

**THe Dot Product**

In [64]:
a1=np.arange(1,7)
X=tf.constant(a1,shape=(3,2))
a2=np.arange(7,13)
Y=tf.constant(a2,shape=(3,2))
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>, <tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [65]:
X@Y

InvalidArgumentError: ignored

In [66]:
tf.transpose(Y) @X

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[ 89, 116],
       [ 98, 128]])>

In [67]:

tf.tensordot(tf.transpose(X),Y,axes=1) #X transposed

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[ 89,  98],
       [116, 128]])>

In [68]:
tf.matmul(tf.transpose(X),Y)#Default axes=1

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[ 89,  98],
       [116, 128]])>

In [69]:
tf.matmul(X,tf.transpose(Y))#Y transpose

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [70]:
#Now Reshaping
tf.matmul(X,tf.reshape(Y,shape=(2,3))) #Transpose and rehsape gives different results

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [71]:
#Value of Y,reshape and Transposed Y
print("Normal Y:")
print(Y,"\n")
print("Transposed Y:")
print(tf.transpose(Y),"\n")
print("Reshaped Y:")
print(tf.reshape(Y,shape=(2,3)))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int64) 

Transposed Y:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int64) 

Reshaped Y:
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int64)


In [72]:
#Generally transpose the tensors instead of reshaping them in matrix multlipication

#Changing the datatype of Tensor

In [73]:

#Create a new tensor with default datatype(default,flot 32)
B=tf.constant([1.7,7.4])
B,B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [74]:
C=tf.constant([7,10])
C.dtype

tf.int32

In [75]:


#change float 32 to 16 (reduced precision) 
D=tf.cast(B,dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [76]:

#int to flot 
E=tf.cast(C,dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

##Aggregating Tensors
AT=condensing them from multiple values to a smaller amount of values.

In [77]:
#Get the absolute values (not best method tho)
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [78]:
#Get the absolute values(turn neg nums in tensors into +ve values)
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>


###Lets go thrgh the following forms of aggretion:
* Get the minimum
* maximum
* mean
* sum of tensor

In [79]:



#creating random tensor with values between 0 and 100 of size 50
import numpy as np
E=tf.constant(np.random.randint(0,101,50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 42,  11,  29,  88,  92,  83,   3,  46,  89,  41,   3,  64,  13,
        82,  76,  83,  88,  81,  26,  48,  56,  48,  45,  77,  96,  16,
         1,  43,  35,  38,  40,  19,  65,  29,  81,  92,  46,  51,   9,
        98,  89,  95,  42,  25,  54,  65,  47,  95, 100,  16])>

In [80]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [81]:
#Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [82]:
#Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=100>

In [83]:
#Find mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=54>

In [84]:
#Find sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2701>

In [85]:
#Find varience ,1st method 
tf.math.reduce_variance(E) #Convert E to float32


TypeError: ignored

In [86]:
E1=E
E=tf.cast(E,dtype=tf.float32)
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float32, numpy=887.89954>

In [87]:
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=29.797644>

In [88]:
#2nd method
import tensorflow_probability as tfp
tfp.stats.variance(E1)

<tf.Tensor: shape=(), dtype=int64, numpy=887>

###Finding Positional Maximum and Minimum

In [89]:
#Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [90]:

#Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [91]:
#Index our largest value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [92]:

#Max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [93]:

#Check for equality
F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [94]:

#Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [95]:
#Find the minimum
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single Dimensions)

In [96]:
#Create a tensor to get started
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [97]:
G.ndim

5

In [98]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [99]:
G_squeezed=tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

##One hot encoding

In [100]:
#Create a list of indices
some_list=[0,1,2,3]#Red ,green , blue , purple
#One hot encode our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [101]:
#Specify custom value for one hot encoding
tf.one_hot(some_list,depth=4,on_value="Meh",off_value="Nah")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Meh', b'Nah', b'Nah', b'Nah'],
       [b'Nah', b'Meh', b'Nah', b'Nah'],
       [b'Nah', b'Nah', b'Meh', b'Nah'],
       [b'Nah', b'Nah', b'Nah', b'Meh']], dtype=object)>

### Squaring,Log,Square root

In [102]:
#Create a new tensor
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [103]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [104]:
#Find squareroot
tf.math.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [105]:
#log
tf.math.log(tf.cast(H,dtype=tf.float32))#Without typecast it will throw error

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and Numpy
Tensorflow interacts beautifully with Numpy arrays ,Tensorflow tensor can run on GPU and TPU for faster numerical processing 

In [106]:
# Create a tensor directly from numpy array
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [107]:
#Convert our tensor back to Numpy array
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [108]:
#Convert Tensor J to Numpy array
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [109]:
numpy_J=tf.constant(np.array([3.,7.,10.]))
tensor_J=tf.constant([3.,7.,10.])
numpy_J.dtype,tensor_J.dtype #Different dtypes from numpy and python list

(tf.float64, tf.float32)

#Finding access to GPU

In [110]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [111]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [112]:
!nvidia-smi

Sat Oct 22 12:43:39 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   70C    P0    30W /  70W |    314MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [113]:
## If u have access to cuda enabled GpU,Tf will use it whenever possible


##  00. TensorFlow Fundamentals Exercises

In [114]:
#Ques 1 : Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
scalar1=tf.constant(1)
scalar1 

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [115]:
vector1=tf.constant([13,15])
vector1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([13, 15], dtype=int32)>

In [116]:
matrix1=tf.constant(np.arange(1,26),shape=(5,5))
matrix1

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])>

In [117]:
#Ques2:Find the shape, rank and size of the tensors you created in 1.
scalar1.shape,scalar1.ndim,tf.size(scalar1)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [118]:
vector1.shape,vector1.ndim,tf.size(vector1)

(TensorShape([2]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [119]:
matrix1.shape,matrix1.ndim,tf.size(matrix1)

(TensorShape([5, 5]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=25>)

In [120]:
#Ques3:Create two tensors containing random values between 0 and 1 with shape [5, 300]
np.random.seed(42)
tensor1=tf.constant(np.random.rand(5, 300),shape=(5,300))
tensor1

<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
array([[0.37454012, 0.95071431, 0.73199394, ..., 0.21582103, 0.62289048,
        0.08534746],
       [0.05168172, 0.53135463, 0.54063512, ..., 0.17231987, 0.19228902,
        0.04086862],
       [0.16893506, 0.27859034, 0.17701048, ..., 0.89633582, 0.01300192,
        0.08550853],
       [0.20788626, 0.0265322 , 0.18143544, ..., 0.96887786, 0.74965183,
        0.13008624],
       [0.7582632 , 0.02458692, 0.02212355, ..., 0.46349404, 0.37978578,
        0.86333365]])>

In [121]:
np.random.seed(41)
tensor2=tf.constant(np.random.rand(5, 300),shape=(5,300))
tensor2

<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
array([[0.25092362, 0.04609582, 0.67681624, ..., 0.86866445, 0.63961138,
        0.30331512],
       [0.93113079, 0.36912563, 0.08470469, ..., 0.14368004, 0.70108794,
        0.29700605],
       [0.16889467, 0.21957451, 0.89407856, ..., 0.25040488, 0.31362211,
        0.64554051],
       [0.4290686 , 0.52244654, 0.32407732, ..., 0.81280229, 0.8282042 ,
        0.91974317],
       [0.50117649, 0.98889197, 0.33721703, ..., 0.51910311, 0.5849142 ,
        0.70623662]])>

In [122]:
tensor1==tensor2

<tf.Tensor: shape=(5, 300), dtype=bool, numpy=
array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])>

In [123]:
tensor1.shape,tensor2.shape

(TensorShape([5, 300]), TensorShape([5, 300]))

In [124]:
# 4: Multiply the two tensors you created in 3 using matrix multiplication.
tensor1@tf.transpose(tensor2)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[73.96315032, 71.31209115, 76.75311558, 73.64912266, 78.04432718],
       [79.05559737, 73.23913446, 79.03991486, 72.38004104, 79.00835378],
       [70.50516726, 67.38967197, 70.93496888, 67.88845975, 71.93006093],
       [76.31920571, 73.67993544, 77.53867265, 76.11577198, 78.19304768],
       [71.86253507, 70.90211704, 77.18527138, 71.60456526, 76.11648042]])>

In [125]:
tf.reduce_max(tensor1)

<tf.Tensor: shape=(), dtype=float64, numpy=0.9997176732861306>

In [126]:
tf.reduce_max(tensor2)

<tf.Tensor: shape=(), dtype=float64, numpy=0.9998057898575213>

In [127]:
tf.matmul(tensor1,tf.transpose(tensor2))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[73.96315032, 71.31209115, 76.75311558, 73.64912266, 78.04432718],
       [79.05559737, 73.23913446, 79.03991486, 72.38004104, 79.00835378],
       [70.50516726, 67.38967197, 70.93496888, 67.88845975, 71.93006093],
       [76.31920571, 73.67993544, 77.53867265, 76.11577198, 78.19304768],
       [71.86253507, 70.90211704, 77.18527138, 71.60456526, 76.11648042]])>

In [128]:
#5 : Multiply the two tensors you created in 3 using dot product. 
tf.tensordot(tensor1,tf.transpose(tensor2),axes=1) #Axes1=simple dot product

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[73.96315032, 71.31209115, 76.75311558, 73.64912266, 78.04432718],
       [79.05559737, 73.23913446, 79.03991486, 72.38004104, 79.00835378],
       [70.50516726, 67.38967197, 70.93496888, 67.88845975, 71.93006093],
       [76.31920571, 73.67993544, 77.53867265, 76.11577198, 78.19304768],
       [71.86253507, 70.90211704, 77.18527138, 71.60456526, 76.11648042]])>

In [129]:
#6:Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tf.random.set_seed(42)
tensor3=tf.random.uniform(shape=(224,224,3),minval=0,maxval=1)
tensor3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 ],
        [0.46448255, 0.03366041, 0.68467236],
        [0.74011743, 0.8724445 , 0.22632635],
        ...,
        [0.42612267, 0.09686017, 0.16105258],
        [0.1487099 , 0.04513884, 0.9497483 ],
        [0.4393103 , 0.28527975, 0.96971095]],

       [[0.73308516, 0.5657046 , 0.33238935],
        [0.8838178 , 0.87544763, 0.56711245],
        [0.8879347 , 0.47661996, 0.42041814],
        ...,
        [0.7716515 , 0.9116473 , 0.3229897 ],
        [0.43050945, 0.83253574, 0.45549798],
        [0.29816985, 0.9639522 , 0.3316357 ]],

       [[0.41132426, 0.2179662 , 0.53570235],
        [0.5112119 , 0.6484759 , 0.8894886 ],
        [0.42459428, 0.20189774, 0.85781324],
        ...,
        [0.02888799, 0.3995477 , 0.11355484],
        [0.68524575, 0.04945195, 0.17778492],
        [0.97627187, 0.79811585, 0.9411576 ]],

       ...,

       [[0.9019445 , 0.27011132, 0.8090267 ],
        [0.32

In [130]:
#7 Find the min and max values of the tensor you created in 6 along the first axis.
tf.reduce_min(tensor3,axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[3.08728218e-03, 3.35657597e-03, 3.03745270e-04],
       [2.07266808e-02, 4.31776047e-04, 1.91926956e-04],
       [1.14024878e-02, 1.01062059e-02, 6.09242916e-03],
       [4.06265259e-04, 6.21199608e-03, 3.45444679e-03],
       [6.39915466e-03, 8.58688354e-03, 1.44493580e-03],
       [1.61790848e-03, 1.22084618e-02, 1.14864111e-02],
       [4.93729115e-03, 1.96862221e-03, 8.63945484e-03],
       [1.54995918e-03, 4.75943089e-03, 1.14287138e-02],
       [4.12750244e-03, 2.41160393e-03, 2.58970261e-03],
       [5.30874729e-03, 4.39548492e-03, 5.05447388e-04],
       [7.61234760e-03, 4.31275368e-03, 4.58204746e-03],
       [4.75323200e-03, 1.07632875e-02, 6.26456738e-03],
       [2.37929821e-03, 1.08909607e-03, 6.28829002e-04],
       [2.86233425e-03, 2.10285187e-04, 2.23445892e-03],
       [5.92350960e-04, 6.08563423e-04, 1.82008743e-03],
       [7.75337219e-03, 4.35113907e-03, 6.29305840e-04],
       [2.28178501e-03, 1.01383924e-02

In [131]:
tf.reduce_max(tensor3,axis=1)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.9982879 , 0.991555  , 0.99890864],
       [0.9963852 , 0.99686027, 0.99524415],
       [0.99798036, 0.99789786, 0.9771793 ],
       [0.9925841 , 0.9995371 , 0.996261  ],
       [0.99925447, 0.99854064, 0.98959684],
       [0.99632823, 0.9975462 , 0.9966078 ],
       [0.99893224, 0.99789345, 0.9986447 ],
       [0.99387276, 0.99100804, 0.99803686],
       [0.99614084, 0.99962425, 0.99817014],
       [0.9990084 , 0.99642086, 0.9947417 ],
       [0.99766946, 0.99010587, 0.9985434 ],
       [0.99462116, 0.9989265 , 0.9968679 ],
       [0.9953896 , 0.99844146, 0.997231  ],
       [0.9752687 , 0.99830484, 0.98452115],
       [0.9964744 , 0.99982226, 0.99907696],
       [0.99845874, 0.9961201 , 0.99886775],
       [0.9960511 , 0.99431336, 0.9901949 ],
       [0.99995625, 0.9980805 , 0.99942625],
       [0.97499347, 0.9930481 , 0.9978708 ],
       [0.998369  , 0.99853635, 0.9970608 ],
       [0.9999449 , 0.9973831 , 0.9944471 ],
     

In [134]:
#8: Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tensor3=tf.expand_dims(tensor3,axis=0)

In [135]:
tensor3.shape

TensorShape([1, 224, 224, 3])

In [136]:
tensor3

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 ],
         [0.46448255, 0.03366041, 0.68467236],
         [0.74011743, 0.8724445 , 0.22632635],
         ...,
         [0.42612267, 0.09686017, 0.16105258],
         [0.1487099 , 0.04513884, 0.9497483 ],
         [0.4393103 , 0.28527975, 0.96971095]],

        [[0.73308516, 0.5657046 , 0.33238935],
         [0.8838178 , 0.87544763, 0.56711245],
         [0.8879347 , 0.47661996, 0.42041814],
         ...,
         [0.7716515 , 0.9116473 , 0.3229897 ],
         [0.43050945, 0.83253574, 0.45549798],
         [0.29816985, 0.9639522 , 0.3316357 ]],

        [[0.41132426, 0.2179662 , 0.53570235],
         [0.5112119 , 0.6484759 , 0.8894886 ],
         [0.42459428, 0.20189774, 0.85781324],
         ...,
         [0.02888799, 0.3995477 , 0.11355484],
         [0.68524575, 0.04945195, 0.17778492],
         [0.97627187, 0.79811585, 0.9411576 ]],

        ...,

        [[0.9019445 , 0.27011132, 

In [138]:
tensor3=tf.squeeze(tensor3)
tensor3.shape

TensorShape([224, 224, 3])

In [145]:
#9: Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tf.random.set_seed(42)
tensor4=tf.random.uniform(shape=(10,1),minval=1,maxval=100,dtype=tf.int32)

In [148]:
tensor4

<tf.Tensor: shape=(10, 1), dtype=int32, numpy=
array([[26],
       [51],
       [36],
       [ 4],
       [62],
       [21],
       [ 8],
       [35],
       [53],
       [97]], dtype=int32)>

In [149]:
tf.one_hot(tensor4,depth=10)

<tf.Tensor: shape=(10, 1, 10), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]], dtype=float32)>

In [150]:
tf.argmax(tensor4)

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([9])>

In [151]:
tf.reduce_max(tensor4)

<tf.Tensor: shape=(), dtype=int32, numpy=97>